// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package telephony.core.query.filter;

import java.util.Date;

public class ComplaintFilterCriteriaBuilder extends
		ComplaintFilterCriteriaBuilderBase<ComplaintFilterCriteriaBuilder> {
	public static ComplaintFilterCriteriaBuilder complaintFilterCriteria() {
		return new ComplaintFilterCriteriaBuilder();
	}

	public ComplaintFilterCriteriaBuilder() {
		super(new ComplaintFilterCriteria());
	}

	public ComplaintFilterCriteria build() {
		return getInstance();
	}
}

class ComplaintFilterCriteriaBuilderBase<GeneratorT extends ComplaintFilterCriteriaBuilderBase<GeneratorT>> {
	private ComplaintFilterCriteria instance;

	protected ComplaintFilterCriteriaBuilderBase(
			ComplaintFilterCriteria aInstance) {
		instance = aInstance;
	}

	protected ComplaintFilterCriteria getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLabel(String aValue) {
		instance.setTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withReportedDateFrom(Date aValue) {
		instance.setReportedDateFrom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withReportedDateTo(Date aValue) {
		instance.setReportedDateTo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPhoneNumber(String aValue) {
		instance.setPhoneNumber(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}
}
