// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package telephony.core.query.filter;

import java.util.Date;

public class DeliveryFilterCriteriaBuilder extends
		DeliveryFilterCriteriaBuilderBase<DeliveryFilterCriteriaBuilder> {
	public static DeliveryFilterCriteriaBuilder deliveryFilterCriteria() {
		return new DeliveryFilterCriteriaBuilder();
	}

	public DeliveryFilterCriteriaBuilder() {
		super(new DeliveryFilterCriteria());
	}

	public DeliveryFilterCriteria build() {
		return getInstance();
	}
}

class DeliveryFilterCriteriaBuilderBase<GeneratorT extends DeliveryFilterCriteriaBuilderBase<GeneratorT>> {
	private DeliveryFilterCriteria instance;

	protected DeliveryFilterCriteriaBuilderBase(DeliveryFilterCriteria aInstance) {
		instance = aInstance;
	}

	protected DeliveryFilterCriteria getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeliveryDateStart(Date aValue) {
		instance.setDeliveryDateStart(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeliveryDateEnd(Date aValue) {
		instance.setDeliveryDateEnd(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSumFrom(Double aValue) {
		instance.setSumFrom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSumTo(Double aValue) {
		instance.setSumTo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeliveredBy(Long aValue) {
		instance.setDeliveredBy(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRegisteredBy(Long aValue) {
		instance.setRegisteredBy(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLabel(String aValue) {
		instance.setLabel(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMinNumberOfProducts(Integer aValue) {
		instance.setMinNumberOfProducts(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMaxNumberOfProducts(Integer aValue) {
		instance.setMaxNumberOfProducts(aValue);

		return (GeneratorT) this;
	}
}
