// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package telephony.core.query.filter;

import java.util.Collection;
import java.util.Date;
import telephony.core.entity.jpa.ProductStatus;

public class ProductFilterCriteriaBuilder extends
		ProductFilterCriteriaBuilderBase<ProductFilterCriteriaBuilder> {
	public static ProductFilterCriteriaBuilder productFilterCriteria() {
		return new ProductFilterCriteriaBuilder();
	}

	public ProductFilterCriteriaBuilder() {
		super(new ProductFilterCriteria());
	}

	public ProductFilterCriteria build() {
		return getInstance();
	}
}

class ProductFilterCriteriaBuilderBase<GeneratorT extends ProductFilterCriteriaBuilderBase<GeneratorT>> {
	private ProductFilterCriteria instance;

	protected ProductFilterCriteriaBuilderBase(ProductFilterCriteria aInstance) {
		instance = aInstance;
	}

	protected ProductFilterCriteria getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withProductsIds(Collection<Long> productsIds) {
		instance.getProductIds().addAll(productsIds);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withProductId(Long productId) {
		instance.addProductId(productId);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withImei(String aValue) {
		instance.setImei(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withProducer(String aValue) {
		instance.setProducer(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withModel(String aValue) {
		instance.setModel(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withColor(String aValue) {
		instance.setColor(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withStoreId(Long aValue) {
		instance.setStoreId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeliveryDateStart(Date aValue) {
		instance.setDeliveryDateStart(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeliveryDateEnd(Date aValue) {
		instance.setDeliveryDateEnd(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withStatus(ProductStatus aValue) {
		instance.setStatus(aValue);

		return (GeneratorT) this;
	}
}
