// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package telephony.core.query.filter;

public class RoleFilterCriteriaBuilder extends
		RoleFilterCriteriaBuilderBase<RoleFilterCriteriaBuilder> {
	public static RoleFilterCriteriaBuilder roleFilterCriteria() {
		return new RoleFilterCriteriaBuilder();
	}

	public RoleFilterCriteriaBuilder() {
		super(new RoleFilterCriteria());
	}

	public RoleFilterCriteria build() {
		return getInstance();
	}
}

class RoleFilterCriteriaBuilderBase<GeneratorT extends RoleFilterCriteriaBuilderBase<GeneratorT>> {
	private RoleFilterCriteria instance;

	protected RoleFilterCriteriaBuilderBase(RoleFilterCriteria aInstance) {
		instance = aInstance;
	}

	protected RoleFilterCriteria getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPage(Integer aValue) {
		instance.setPage(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPerPage(Integer aValue) {
		instance.setPerPage(aValue);

		return (GeneratorT) this;
	}
}
