// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package telephony.core.query.filter;

import java.util.Collection;
import java.util.Date;

public class TaxFilterCriteriaBuilder extends
		TaxFilterCriteriaBuilderBase<TaxFilterCriteriaBuilder> {
	public static TaxFilterCriteriaBuilder taxFilterCriteria() {
		return new TaxFilterCriteriaBuilder();
	}

	public TaxFilterCriteriaBuilder() {
		super(new TaxFilterCriteria());
	}

	public TaxFilterCriteria build() {
		return getInstance();
	}
}

class TaxFilterCriteriaBuilderBase<GeneratorT extends TaxFilterCriteriaBuilderBase<GeneratorT>> {
	private TaxFilterCriteria instance;

	protected TaxFilterCriteriaBuilderBase(TaxFilterCriteria aInstance) {
		instance = aInstance;
	}

	protected TaxFilterCriteria getInstance() {
		return instance;
	}


	@SuppressWarnings("unchecked")
	public GeneratorT withTaxIds(Collection<Long> ids) {
		instance.getTaxIds().addAll(ids);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTaxId(Long taxId) {
		instance.addTaxId(taxId);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTaxDateStart(Date aValue) {
		instance.setTaxDateStart(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTaxDateEnd(Date aValue) {
		instance.setTaxDateEnd(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRateFrom(Double aValue) {
		instance.setRateFrom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRateTo(Double aValue) {
		instance.setRateTo(aValue);

		return (GeneratorT) this;
	}
}
