// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package telephony.core.query.filter;

public class UserFilterCriteriaBuilder extends
		UserFilterCriteriaBuilderBase<UserFilterCriteriaBuilder> {
	public static UserFilterCriteriaBuilder userFilterCriteria() {
		return new UserFilterCriteriaBuilder();
	}

	public UserFilterCriteriaBuilder() {
		super(new UserFilterCriteria());
	}

	public UserFilterCriteria build() {
		return getInstance();
	}
}

class UserFilterCriteriaBuilderBase<GeneratorT extends UserFilterCriteriaBuilderBase<GeneratorT>> {
	private UserFilterCriteria instance;

	protected UserFilterCriteriaBuilderBase(UserFilterCriteria aInstance) {
		instance = aInstance;
	}

	protected UserFilterCriteria getInstance() {
		return instance;
	}
}
